### ISSUE TITLE
Multiple Category Types

### ISSUE THREAD

**Issue by thetre97** [pasdo501/gatsby-source-woocommerce#1]
Firstly, thanks for keeping this plugin updated!

When i run Gatsby, it throws these error messages at me.

`gatsby-config.js`
```javascript
{
      resolve: '@pasdo501/gatsby-source-woocommerce',
      options: {
       // Base URL of Wordpress site
        api: 'mysite.com/wordpress',
        // true if using https. false if nah.
        https: true,
        api_keys: {
          consumer_key: 'key-with-read-permissions',
          consumer_secret: 'key-with-read-permissions',
        },
        // Array of strings with fields you'd like to create nodes for...
        fields: ['products'],
        // Version of the woocommerce API to use
        // OPTIONAL: defaults to 'wc/v1'
        api_version: ['wc/v3'],
        // OPTIONAL: How many results to retrieve
        per_page: 100
      }
    },
```
```bash
Path: /wordpress/wp-json/wc/v1/products/categories?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "Sorry, you cannot list resources."
⠂ source and transform nodes
Path: /wordpress/wp-json/wc/v1/products/tags?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "Sorry, you cannot list resources."
⠂ source and transform nodes
Path: /wordpress/wp-json/wc/v2/products/categories?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "Sorry, you cannot list resources."
⢀ source and transform nodes
Path: /wordpress/wp-json/wc/v2/products/tags?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "Sorry, you cannot list resources."
⡀ source and transform nodes
Path: /wordpress/wp-json/wc/v3/products/categories?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "Sorry, you cannot list resources."
⡀ source and transform nodes
Path: /wordpress/wp-json/wc/v3/products/tags?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "Sorry, you cannot list resources."
```

Even though it specifies `wc/v3` and I'm not asking for categories or tags. If i then add those to the array `['products/categories', 'products/tags']`, it complains that there are multiple types:

```bash
Error: Schema must contain uniquely named types but contains multiple types named "wcProductsCategories".
```

**Comment by pasdo501** [comment]
Hello!

Thanks for the comment, I'll look into it.

Straight away I can see that my documentation is wrong, the line 

```api_version: ['wc/v3']```

should actually be

```api_version: 'wc/v3'```

So that might explain why it's trying to get the wrong version (although, disclaimer: changing from one to the other seems to have no effect for me in a test repository -- the woocommerce api package might be able to handle it in either format, I guess). 

The error messages look like the ones you get when you try to access the WooCommerce routes without the right keys (e.g. just browsing to <your-site>/wp-json/wc/v2/products), which makes me think it may have be related to the consumer key / secret?

The multiple types named wcProductsCategories I believe is possibly linked to it trying to get multiple versions of the data (v1,v2,v3) -- which may or may not get resolved when changing the way the API version is given (I have a feeling it won't be).

None of this explains why it's attempting to get fields you haven't specified though, it should only be getting what's in the fields array. 

Is there any chance it's gatsby-source-wordpress trying to grab all these things as well? I get very similar error messages if I include products, for example, in the gatsby-source-wordpress included routes (assuming you use that plugin, of course). If so, does adding the woocommerce fields to the excluded routes solve anything?

**Comment by thetre97** [comment]
Yes, I noticed that about the versions - I was about to make a PR for that :)

> So that might explain why it's trying to get the wrong version (although, disclaimer: changing from one to the other seems to have no effect for me in a test repository -- the woocommerce api package might be able to handle it in either format, I guess).

Could well be that - I changed the line `version: api_version || 'wc/v1'` and hardcoded the value to `'wc/v3'`, and it stopped trying to get all versions of the API. Specifying a default value like this seems to work:

```javascript
const { api, https, api_keys, fields, api_version = 'wc/v1', per_page } = configOptions

  // set up WooCommerce node api tool
  const WooCommerce = new WooCommerceAPI({
    url: `http${https ? "s" : ""}://${api}`,
    consumerKey: api_keys.consumer_key,
    consumerSecret: api_keys.consumer_secret,
    wpAPI: true,
    version: api_version,
  })
```

**Comment by thetre97** [comment]
I also tried adding the `wc` route to the wordpress plugin blacklist, and even tried removing the plugin completely, but I still get the same issue. I found that even if I don't add `'products/categories'` to the array, it still creates that type in the schema:

![image](https://user-images.githubusercontent.com/12587127/55550822-288d1900-56d1-11e9-9d2d-0da11fa94c96.png)

I wonder if it is anything to do with the helper that creates relationships between products and categories, in the helper file? (L24).

**Comment by thetre97** [comment]
I managed to get it working by adding this hacky bit of code 🙂 :

```javascript
let fieldName = normaliseFieldName(field)
if (fieldName === 'productsCategories') fieldName = 'categories'
```

And no more errors are thrown and I can get product categories 🎉 I think it must be because of the helper code that creates the relationships for products runs before categories are sourced, so it is creating the type first...?

**Comment by pasdo501** [comment]
Thanks for the work on this!

I wasn't seeing the issue initially on the project I'm currently working on (although I do remember now actually that I did see that at some point and changed the name from wc to Wc and then back again, and then never saw the problem again, and remember thinking ... that was weird).

Setting up a fresh starter with source-wordpress & this plugin, I could pull in products fine, but as soon as I added 'products/fields' - there was the issue! After trying a couple of different things, I've come to the conclusion that on products, the existing categories field (which is the standard object containing id (the cat ID), slug & name or something along those lines) was somehow getting assigned the wcProductsCategories type at some point after the plugin's work was done, presumably during the schema creation run by gatsby. I'm just guessing here, but it seems like base type wcProducts just had the 'Categories' appended when it came to that field? This is based on the following field on products in the schema, even when it's just products being pulled in:

![image](https://user-images.githubusercontent.com/28074672/55596756-a8d17e00-57a6-11e9-9b15-c873a2352248.png)


Since that type now already existed, it then couldn't create it again when it came to the _actual_ category nodes. Deleting the original categories field seems to solve the issue, at least in my tests! :tada:

I still don't quite understand why I wasn't getting this issue in my current project anymore, some sort of caching going on. It didn't crop up even after removing gatsby clean, but I suppose it might be cached in a different way. My fault for not setting up a fresh testing repo!

If you have the time, would you mind pulling down the most recent commit ae062d7fbfd97477f37acbe02e755d5d937d410c to see if that also fixes your issue without the workaround of renaming the field?

**Comment by thetre97** [comment]
Just tried using the latest commit - 👏 👏 that is working great now.. thanks!

**Comment by thetre97** [comment]
On a slightly different note, I was wondering about updating the readme to show integration with Gatsby Image - similar to https://github.com/datocms/gatsby-source-datocms#integration-with-gatsby-image, if you think that is a good idea?

**Comment by pasdo501** [comment]
> Just tried using the latest commit - :clap: :clap: that is working great now.. thanks!

Awesome! Thank you so much for finding the issue and helping to resolve it. I'll update the package on NPM now.

> On a slightly different note, I was wondering about updating the readme to show integration with Gatsby Image - similar to https://github.com/datocms/gatsby-source-datocms#integration-with-gatsby-image, if you think that is a good idea?

Sure, yeah! It's probably kinda confusing the way I have it written as just

```
...
localFile {
            // childImageSharp ... etc
          }
...
```

Especially if read by people who maybe haven't come across Gatsby Image yet
