### ISSUE TITLE
The "product_variations" key doesn't appear

### ISSUE THREAD

**Issue by nickrigby** [pasdo501/gatsby-source-woocommerce#14]
With a WordPress 5.2.3 install, running WooCommerce 3.7.0, I don't see the `product_variations` key on the `wcProducts` query. Tried all versions for the `api_version` setting and still no luck. Do you have any ideas on why it might now be appearing?

Many thanks for your help!

**Comment by pasdo501** [comment]
Hey mate,

I just spun up a new local site with the latest versions of WooCommerce & WordPress, and I'm seeing the product_variations, so unfortunately I'm not getting the same issue. 

![image](https://user-images.githubusercontent.com/28074672/65934328-5af5b400-e471-11e9-8bd5-2257afe1daa1.png)

Are you getting any warnings at all? Just to cover all bases - I assume there is at least one variable product in your product list?

Hopefully we can get to the bottom of it!

**Comment by nickrigby** [comment]
Thanks for the info! I think I've figured it out. There has to be at least one variable product in the per page fetch, otherwise it doesn't appear at all. For example, I have over 600 products in my catalog. If I leave the `per_page` option at 10, my variable product isn't in that first page so the `product_variations` key doesn't appear in the GraphQLi. If I increase it to 100, both of my variable products are luckily in that page fetch, and the option appears. So it seems that at least one variable product needs to be in that first page fetch for it to work.

Hope that makes sense! Wondering if there's a way it could work regardless of where in the catalog a variable product appears?

Many thanks again for your response and for building this!

**Comment by pasdo501** [comment]
Yes - that makes perfect sense! I'm currently thinking, maybe I could change the fetching behaviour to grab all the products at once (just do multiple fetches if there are more products  - I assume the woocommerce api will return something to allow checking how much data there is in total, although I haven't yet checked that).

I'll see about looking into that!

**Comment by pasdo501** [comment]
Hey mate,

I've made some changes to the plugin that _should_ solve the issue you came across. I've changed the behaviour so the plugin pulls in all of the resources for each field, rather than stopping at the limit set by per_page (in hindsight actually how it should work - I think I was under the impression it'd just keep pulling them in past that point anyway, but it would have been limited to 100?). Let me know if that sort of behaviour breaks what your use case at all, although I suspect it won't cause any issues since even if it did, one could always just limit the total pulled in through the graphQL query anyway ...

Anyway, if you get a chance, I'd appreciate it if you would be able to test the new version (would just have to be pulled from here at the moment rather than through npm since I haven't pushed the update there yet). It's [this branch](https://github.com/pasdo501/gatsby-source-woocommerce/tree/per_page_patch). It's all good with the testing I've done with it, but I don't have a site with that many products handy so that'd be a great opportunity!

Thanks!

**Comment by nickrigby** [comment]
Thanks so much! I'll definitely test and report back if I hit any issues. Really appreciate your help!

**Comment by pasdo501** [comment]
Awesome, thank you! 

Just a side note, you may need to add @woocommerce/woocommerce-rest-api to your project dependencies when testing -- the old woocommerce api is obsolete now so I took the opportunity while changing things anyway to migrate to the new version. I think yarn (probably npm as well) doesn't take those dependencies into account when you mess around in the node_modules folder (since the most up to date version it can get isn't the new one), though, so wouldn't automatically install it when running yarn / npm install. Should work with it as a dependency of the project itself though, and can then be removed once the new version is on npm!

**Comment by nickrigby** [comment]
Hi @pasdo501 

Appears to work like a charm! I dropped the `per_page` option, since it's probably redundant, and manually added the `@woocommerce/woocommerce-rest-api` since I just cloned down the patched branch.

Thank you again for the fix. If I can do anything else to test, please let me know.

Nick

**Comment by pasdo501** [comment]
Fantastic - thank you very much! I've published the new version to npm now. 

`per_page` really does become a redundant option, doesn't it? I suppose the only thing it affects now is how many requests will be made to the WordPress / WooCommerce site during the build. The default is just 10, so that could probably just be put to something like 100 to reduce the number of requests, or re-purpose it at some point for inbuilt pagination - either way, not really too crucial at the moment, I think.

Shout out if you come across any other issues!
