### ISSUE TITLE
Unknown field 'localFile' on type 'wcProductsCategoriesImage'.

### ISSUE THREAD

**Issue by davevanhoorn** [pasdo501/gatsby-source-woocommerce#21]
Hi @pasdo501,

I'm having trouble getting images to show. I get an error when I copy / paste the example queries from the docs, it tells me `Unknown field 'localFile' on type 'wcProductsCategoriesImage'.`.

Running a query without the `localFile` key works fine, but as soon as I add localFile I'm running into errors.

**The GraphQL query:**
```javascript
export const query = graphql`
  query {
    allWcProductsCategories {
      edges {
        node {
          name
          image {
            localFile {
              childImageSharp {
                fluid(maxWidth: 400, maxHeight: 250) {
                  ...GatsbyImageSharpFluid
                }
              }
            }
          }
        }
      }
    }
  }
`
```

**My Gatsby setup:**
```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.15.22 => 2.15.22
    gatsby-image: ^2.2.32 => 2.2.32
    gatsby-plugin-manifest: ^2.2.18 => 2.2.18
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-offline: ^3.0.8 => 3.0.8
    gatsby-plugin-react-helmet: ^3.1.8 => 3.1.8
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sharp: ^2.2.38 => 2.2.38
    gatsby-plugin-styled-components: ^3.1.6 => 3.1.6
    gatsby-plugin-typescript: ^2.1.11 => 2.1.11
    gatsby-source-filesystem: ^2.1.26 => 2.1.26
    gatsby-transformer-sharp: ^2.3.4 => 2.3.4
  npmGlobalPackages:
    gatsby-cli: 2.8.10
```

Am I missing something obvious?

**Comment by davevanhoorn** [comment]
It was the Roots Soil plugin. Disabling this will fix the issue.

**Comment by pasdo501** [comment]
Hi mate,

Was in the middle of writing a reply as you found out the root (ha! sorry, couldn't help myself) of the issue, glad to hear it.

I thought the issue was possibly due to the image field not existing when there are no images other than the default thumbnails set for categories, but actually realise now that you said it worked fine without the `localFile` key (and the `image` key would be where it starts failing if that was the issue).

I wonder how that plugin breaks it!

**Comment by davevanhoorn** [comment]
Sure, happy to test it :)

**Comment by pasdo501** [comment]
Actually, on reading that thread properly to its conclusion it sounds like there's already a retry mechanism built into `createRemoteFileNode` (which is essentially what that pull request was doing; they did say it might require some verification that it works, though). 
I think we can try seeing if it the issue is actually something related to that part of the code first - I'll update this comment with a reference to a commit shortly
