### ISSUE TITLE
Variations details for variable product

### ISSUE THREAD

**Issue by anamwp** [pasdo501/gatsby-source-woocommerce#8]
Hello, 
I tried to show this data. But failed. 
In my single product query which is variable product, when I query for variation it give me id of variation. 
But I need variation price, variation details and other field which is in the image. 
Check the image. 
https://monosnap.com/file/8gY7JM8ycFEPj1kB6E4OVxNvMPUGp0
https://monosnap.com/file/MpG1Itl9EYZkIharVAezmwyL054PZV
I appreciate your help. 
thanks.

**Comment by pasdo501** [comment]
Hello!

You should be able to access variations now. Variable products will have a new field called `products_variations` that will contain the data you need. I've left the `variations` field containing just the IDs alone, in case someone is using it. The issue was that the endpoint has a variable id field in it (`products/<id>/variations`), so it wouldn't be possible to get it using the fields that were set up so far! 

As an example: 

```graphql
{
  wcProducts(wordpress_id: {eq: 13}) {
    wordpress_id
    name
    product_variations {
      id 
      price 
      stock_status
      description
      attributes {
        name
        option
      }
    }
  }
}
```

Should get you what you need. To get the attribute combination that makes up the variation, look at the attributes fields (name, option). If an attribute is missing, it's 'any'. Do note that there's no price_html field in the variations (although the parent product field does still have the price_html field (which, I believe takes the form of something along the lines of  `lowest variation price - highest variation price`).

Let me know if that works for you!
